apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-service
  template:
    metadata:
      labels:
        app: blockchain-service
    spec:
      containers:
      - name: blockchain-service
        image: us-central1-docker.pkg.dev/real-estate-dapp-jee/jee-repo/blockchain-integration-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
spec:
  selector:
    app: blockchain-service
  ports:
  - port: 8080
    targetPort: 8084
