apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental-service
  template:
    metadata:
      labels:
        app: rental-service
    spec:
      containers:
      - name: rental-service
        image: us-central1-docker.pkg.dev/real-estate-dapp-jee/jee-repo/rental-service:latest
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/real_estate_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "password"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://service-discovery:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: rental-service
spec:
  selector:
    app: rental-service
  ports:
  - port: 8080
    targetPort: 8083
