apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-estate-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: real-estate-backend
  template:
    metadata:
      labels:
        app: real-estate-backend
    spec:
      containers:
      - name: backend
        # Ton image stock√©e chez Google
        image: us-central1-docker.pkg.dev/real-estate-dapp-jee/jee-repo/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: real-estate-backend-service
spec:
  type: LoadBalancer # Pour avoir une IP publique
  selector:
    app: real-estate-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080