apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-estate-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: real-estate-frontend
  template:
    metadata:
      labels:
        app: real-estate-frontend
    spec:
      containers:
      - name: frontend
        image: us-central1-docker.pkg.dev/real-estate-dapp-jee/jee-repo/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: real-estate-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: real-estate-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80