server:
  port: 8084

spring:
  application:
    name: blockchain-integration-service

blockchain:
  ethereum:
    node-url: https://sepolia.infura.io/v3/YOUR_INFURA_KEY
    contract-address: 0x0  # Value to be updated
    private-key: 0x0       # Value to be updated

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
